### ISSUE TITLE
undefined method for nil NilClass.

### ISSUE THREAD

**Issue by GusevVictor** [jamesrwhite/minicron#156]
Dear, please fix it. 

`root@minicron:/opt/minicron-0.8-linux-x86_64# ./minicron run --verbose ls`

`error: undefined method '[]' for nil:NilClass.`

**Comment by robinjoseph08** [comment]
Hey,

I was having this issue too, and I was able to fix it by updating my config file (`/etc/minicron.toml` in my case). You can verify if this is your issue too by running `./minicron run --dry-run --verbose ls` and seeing if it runs `ls` correctly.

Originally, I followed the [example config file](https://github.com/jamesrwhite/minicron/blob/master/config/minicron.toml) in the repo, but it looks like it's a bit out of date. Instead of this for your client setup:

```toml
# ...
# Client options
[client]
scheme = "http" # [http, https]
host = "127.0.0.1"
port = 9292
path = "/"
connect_timeout = 5
inactivity_timeout = 5
  [client.cli]
  mode = "line" # [line, char] - line by line output or char by char
  dry_run = false # When true the command is run but not sent to the server
# ...
```

It needs to be nested under `client.server`:

```toml
# ...
# Client options
[client]
  [client.server]
  scheme = "http" # [http, https]
  host = "127.0.0.1"
  port = 9292
  path = "/"
  connect_timeout = 5
  inactivity_timeout = 5
  # CLI options
  [client.cli]
  mode = "line" # [line, char]
  dry_run = false
# ...
```

I found a better example [here](https://github.com/jamesrwhite/minicron/blob/master/spec/valid_config.toml) in the spec directory.

Hope this helps!
